import {MD3DarkTheme, configureFonts} from 'react-native-paper';
import type {MD3Theme} from 'react-native-paper';
import {DTColors} from './colors';
import {DTTypography} from './typography';

const fontConfig = {
  displayLarge: DTTypography.displayLarge,
  displayMedium: DTTypography.displayMedium,
  displaySmall: DTTypography.displaySmall,
  headlineLarge: DTTypography.headlineLarge,
  headlineMedium: DTTypography.headlineMedium,
  headlineSmall: DTTypography.headlineSmall,
  titleLarge: DTTypography.titleLarge,
  titleMedium: DTTypography.titleMedium,
  titleSmall: DTTypography.titleSmall,
  bodyLarge: DTTypography.bodyLarge,
  bodyMedium: DTTypography.bodyMedium,
  bodySmall: DTTypography.bodySmall,
  labelLarge: DTTypography.labelLarge,
  labelMedium: DTTypography.labelMedium,
  labelSmall: DTTypography.labelSmall,
};

export const DTTheme: MD3Theme = {
  ...MD3DarkTheme,
  dark: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: DTColors.modeNormal,
    onPrimary: DTColors.dark,
    primaryContainer: DTColors.modeNormalSelected,
    onPrimaryContainer: DTColors.dark,
    secondary: DTColors.modeEmphasis,
    onSecondary: DTColors.dark,
    secondaryContainer: DTColors.modeEmphasisSelected,
    onSecondaryContainer: DTColors.dark,
    tertiary: DTColors.modeOther,
    onTertiary: DTColors.dark,
    tertiaryContainer: 'rgba(255, 0, 255, 0.3)',
    onTertiaryContainer: DTColors.light,
    error: DTColors.modeWarning,
    onError: DTColors.dark,
    errorContainer: 'rgba(255, 0, 0, 0.3)',
    onErrorContainer: DTColors.light,
    background: DTColors.dark,
    onBackground: DTColors.light,
    surface: DTColors.dark,
    onSurface: DTColors.light,
    surfaceVariant: '#1a1a1a',
    onSurfaceVariant: DTColors.light,
    outline: DTColors.modeNormal,
    outlineVariant: 'rgba(0, 255, 255, 0.3)',
    inverseSurface: DTColors.light,
    inverseOnSurface: DTColors.dark,
    inversePrimary: '#008888',
    elevation: {
      level0: 'transparent',
      level1: '#0a0a0a',
      level2: '#121212',
      level3: '#1a1a1a',
      level4: '#1e1e1e',
      level5: '#222222',
    },
    surfaceDisabled: 'rgba(255, 255, 255, 0.12)',
    onSurfaceDisabled: 'rgba(255, 255, 255, 0.38)',
    backdrop: 'rgba(0, 0, 0, 0.5)',
    shadow: DTColors.dark,
    scrim: DTColors.dark,
  },
  fonts: configureFonts({config: fontConfig}),
};
